Distgit to Delivery Repo mappings
openshift/art-bot pull request #16
Opened 2022-06-09 15:31 UTC by ashwindasr

Map Distgit repo name to Delivery repo name starting from the former.

2022-06-09 21:47 UTC, sosiouxme requested changes
a promising start; some things to try/discuss

2022-06-09 21:47 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +    response = requests.get(f"https://pkgs.devel.redhat.com/cgit/containers/{distgit_repo_name}")
if you just need the status code then a `.head` request is quicker/kinder (doesn't have to generate the page)

2022-06-09 21:47 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        version = "4.11"  # Default version set to 4.11, if unspecified
should be 4.10 for now since we've shipped that and CDN repos are configured

2022-06-09 21:47 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        cdn_repo_name = brew_to_cdn(brew_package_name, "8Base-RHOSE-4.10")  # Default variant set to 8Base-RHOSE-4.10"
```suggestion
        cdn_repo_name = brew_to_cdn(brew_package_name, f"8Base-RHOSE-{version}")
```

2022-06-09 21:47 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        return json_file['data'][0]['relationships']['cdn_repo']['name']
i suspect there can be more than one entry in `data` but i don't have a ready example to see... note to self to try

2022-06-09 21:47 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        return "Couldn't find CDN repo name."
again would prefer an exception here, with enough information for the caller to be able to tell the user "errata-tool says there's no CDN repo for that in version {version}" or "something unexpected went wrong querying for CDN repo" and write something to `art-bot-monitoring`

and not having a CDN repo is fine, we just can't get past that to find comet repo so we have to tell the user :shrug:

2022-06-09 21:47 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +def check_distgit_availability(distgit_repo_name):
since you're using it like a boolean i'd suggest
```suggestion
def distgit_is_available(distgit_repo_name):
```
or maybe
```suggestion
def distgit_exists(distgit_repo_name):
```

2022-06-09 21:47 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +    else:
i did not seem to reach this branch of logic when I requested a bogus repo. i don't see why not though.

2022-06-09 21:47 UTC, sosiouxme commented on tests/test_pipeline_image_names.py
> +def test_distgit_to_brew_1():
nice to see tests.
technically these are functional/integration tests, since they'll hit the live system for info. so they should go in `functional`. you could also mock out the system calls in order to make them actual unit tests...

2022-06-10 16:11 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +    response = requests.get(f"https://pkgs.devel.redhat.com/cgit/containers/{distgit_repo_name}")
Done!

2022-06-10 16:12 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        version = "4.11"  # Default version set to 4.11, if unspecified
Done!

2022-06-10 16:17 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +def check_distgit_availability(distgit_repo_name):
Done!

2022-06-10 16:22 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +    else:
I added that change with 49d94af17a73eb62be4c849d0df5e9d9c0270fba. Can you check to see if its working again?

![image](https://user-images.githubusercontent.com/20128743/173109248-ef4da2f0-28f6-4a4a-b6b3-2e6e2fda6f02.png)

2022-06-10 16:25 UTC, ashwindasr commented on tests/test_pipeline_image_names.py
> +def test_distgit_to_brew_1():
Done!

2022-06-10 16:26 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +    kerberos_auth = HTTPKerberosAuth(mutual_authentication=REQUIRED, sanitize_mutual_error_response=False)
Okay! So no need to make any changes right?

2022-06-10 16:44 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        return json_file['data'][0]['relationships']['cdn_repo']['name']
You're right. So the API checks only the first page. `openshift-enterprise-console-container` has only one instance in all the pages though. But like you said there could be others in other pages right.  Should I go through all the data and check if there's any other one that has `package_name` as the brew package name and display multiple outputs or ?

2022-06-11 22:20 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        return "Couldn't find Brew Package name"
Done!

2022-06-11 22:24 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        return "Couldn't find CDN repo name."
Okay! I added the custom exception, please check to see if that's okay. Also just to confirm, the function to display to art-bot-monitoring is `so.monitoring_say()` ?

2022-06-11 22:25 UTC, ashwindasr commented
Also need to add links for Brew, CDN and Delivery repos.

2022-06-13 17:46 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +    else:
looks good now, must not have had this update :+1:

2022-06-17 02:30 UTC, ashwindasr commented
Finished adding links to all parts of the pipeline.

2022-06-17 16:31 UTC, sosiouxme requested changes
It would be surprising if I didn't find anything to tweak :)

2022-06-17 16:31 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +    for line in data:
there's a pattern for this...
```suggestion
    dict_data = {}
    for line in output[1].splitlines():
```

2022-06-17 16:31 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        if array != ['']:
seems overly specific. this shouldn't happen with this output and `splitlines()`, but if it did, i'd probably want to ignore more:
```suggestion
        if len(array) == 2:
```

2022-06-17 16:31 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        raise GithubFromDistgitNotFound(distgit_name, version)
this doesn't seem to be getting caught and notified back to user. trying
`What is the image pipeline for distgit aos3-installation with version 3.11`
... just crashes. (Also it should be found... not sure why it's not)

2022-06-17 17:32 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        so.monitoring_say(f"No distgit repo with name *{distgit_repo_name}* exists.")
Inverted logic and removed error logs to monitoring channel

2022-06-17 17:35 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +    if yml_file['for_payload']:
Okay!

2022-06-17 17:37 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +            return tag
Understood!

2022-06-17 17:43 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +def get_github_from_distgit(distgit_name, version):
Makes sense!

2022-06-17 17:44 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +    for line in data:
Ohh I see! Thank you!

2022-06-17 17:46 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        raise GithubFromDistgitNotFound(distgit_name, version)
Yeah I found the issue as well. It was because it was outside the `try` block. Fixed!

2022-06-17 17:56 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        raise GithubFromDistgitNotFound(distgit_name, version)
And regarding why it's not working, it seems to be a doozer issue:
```bash
    raise ValueError(f'{self.distgit_key} claims to be for_release and base_only')
ValueError: openshift-enterprise-base claims to be for_release and base_only
```
for the command `doozer -g openshift-3.11 images:print --short '{name}: {upstream_public}'`

2022-06-17 17:57 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +
Understood. I forgot to clean it before I committed, my bad

2022-06-17 21:38 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        super().__init__(self.message)
Done!

2022-06-17 21:47 UTC, ashwindasr commented
Rebuilt the art-bot container, but `click` version `8.1.3` gets installed instead of `8.1.2`. Found that the version is being pulled from the `requirements.txt` of `art-bot`. Adding a commit to lock it at `8.1.2`

2022-07-01 18:54 UTC, sosiouxme requested changes
other than one bug found, looking pretty good. going to push some cosmetic changes as well as a fix for a totally unrelated bug i found

2022-07-01 18:54 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +    :github_repo: Name of the GitHub repo we get as input
This is optional, but in general if there's more than one obvious way to refer to something, I like to accept any reasonable way.

For this case, I'd consider any of the following equivalent and wasn't sure which to use:
* `ironic-image`
* `openshift/ironic-image`
* `github.com/openshift/ironic-image`
* `https://github.com/openshift/ironic-image.git`
* `https://github.com/openshift/ironic-image/`
* `https://github.com/openshift/ironic-image`

I'd like to see whatever comes in get normalized to the last form and then proceed from that.

2022-07-01 18:54 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        payload += f"No GitHub repo with name *{github_repo}* exists."
It is helpful here to give an example of what it should look like, in case they just didn't know what format to use.

2022-07-01 18:54 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +    :distgit_repo_name: Name of the distgit repo we get as input
Likewise here it would be nice to accept `containers/ironic` which is technically the repo, or `ironic`

(and/or give an example when they get it wrong)

2022-07-01 18:54 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +            payload += pipeline_image_util.brew_to_github(brew_name, version)
There is a bug here somewhere. This got stuck on the way to github:
```
sosiouxme: @art-bot-luke pipeline for package ironic-container in 4.11
art-bot-luke: Fetching data. Please wait...
art-bot-luke: Couldn't find GitHub repo from distgit ironic and version 4.11
```
`ironic` is the correct distgit but it did not map back correctly to GitHub.

2022-07-01 18:54 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        payload += f"No CDN repo with name *{cdn_repo_name}* exists."
no one is really likely to search by this, but if they do... best to give them an example here of what a CDN repo even looks like (they likely don't know)

2022-07-01 18:54 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +    :delivery_repo_name: Name of the delivery repo we get as input
again optional, but I'd expect to accept any of:
* `registry.redhat.io/openshift4/ose-ironic-rhel8`
* `openshift4/ose-ironic-rhel8`
* `ose-ironic-rhel8`

... and/or an example of the expected format

2022-07-05 13:15 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +            payload += pipeline_image_util.brew_to_github(brew_name, version)
Found that the issue was with `cache`.

2022-07-06 19:27 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +    :github_repo: Name of the GitHub repo we get as input
I wrote a regex to match all the above cases, but there seems to be an issue with getting an URL input for the last 3 cases. Slack is sending the data like this:
```
----------------- DATA -----------------

{'blocks': [{'block_id': '8eFd',
             'elements': [{'elements': [{'text': '@art-bot-dev what is the '
                                                 'image pipeline for github ',
                                         'type': 'text'},
                                        {'style': {'unlink': True},
                                         'text': 'https://github.com/openshift/ironic-image.git',
                                         'type': 'text'}],
                           'type': 'rich_text_section'}],
             'type': 'rich_text'}],
```
So its not getting matched with the regex as URL is being sent differently than the text. It works if I manually remove the hyperlink and send the request. Normally the app reads it like this
```
----------------- DATA -----------------

{'channel': 'D03F6UXS5N3',
 'event_ts': '1657135302.007400',
 'hidden': True,
 'message': {'blocks': [{'block_id': 'hjD',
                         'elements': [{'elements': [{'text': '@art-bot-dev '
                                                             'what is the '
                                                             'image pipeline '
                                                             'for distgit '
                                                             'openshift-enterprise-cli',
                                                     'type': 'text'}],
                                       'type': 'rich_text_section'}],
                         'type': 'rich_text'}],
```

2022-07-06 19:47 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +    :github_repo: Name of the GitHub repo we get as input
I wrote a regex to match all the above cases: ```(https:\/\/)*(github.com\/)*(openshift\/)*([a-zA-Z0-9-]+)(.*)```
But when talk to artbot like ```@art-bot-dev what is the image pipeline for github https://github.com/openshift/ironic-image.git```, Slack it converting the URL to hyperlink and I'm getting ```None``` in the backend. It works when I change the URL to plain text in slack though, but I'm not sure if people will actively do that

2022-07-06 21:18 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +    :delivery_repo_name: Name of the delivery repo we get as input
Same hyperlink issue in the first example.

2022-07-06 21:21 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +    :github_repo: Name of the GitHub repo we get as input
![image](https://user-images.githubusercontent.com/20128743/177645577-01d7f08b-92b2-4a15-8de1-821e7c4cb67e.png)

2022-07-11 16:53 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        raise GithubFromDistgitNotFound(distgit_name, version)
https://github.com/openshift/ocp-build-data/commit/15b40758b5f95627c40a85134453ab13bb451b07 should fix that.

2022-07-11 16:54 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +        raise GithubFromDistgitNotFound(distgit_name, version)
technically doozer shouldn't have two attrs that are basically for the same thing but... history :(

2022-07-11 16:55 UTC, sosiouxme commented on artbotlib/pipeline_image_names.py
> +    :github_repo: Name of the GitHub repo we get as input
add in https://github.com/openshift/art-bot/pull/20 which should cause the url to show up in the query

2022-07-11 17:21 UTC, merged