Check PR into nightlies/releases
openshift/art-bot pull request #35
Opened 2022-10-26 13:00 UTC by locriandev

art-bot will answer questions like:
```
pr info for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1388 in 4.9
pr info for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1388 in 4.9 for arm64
```
and will look into nightlies and releases to see if a PR has been included. It will reply with answers like:
```
PR https://github.com/openshift/cluster-kube-apiserver-operator/pull/1388 has been included starting from 4.9.0-0.nightly-2022-10-25-220749

PR https://github.com/openshift/ovn-kubernetes/pull/1336 has not been found in any 4.10 release
```

2022-10-26 20:31 UTC, ashwindasr commented
We have the github-distgit mapping code in the image-pipeline feature. I think we don't have more than 3 components building from the same repo, so we could check for all components and display if they are in releases or not. Even if we are getting the component name as input we'll have to check if the component actually exists before we proceed, so we can reuse the github-distgit mapping code.

2022-10-26 20:35 UTC, ashwindasr commented
Also since doozer is writing to the database again, we can now implement the PR to build part of [the ticket](https://issues.redhat.com/browse/ART-5067) as well. I'll get started on that.

2022-10-26 22:22 UTC, ashwindasr requested changes

2022-10-26 22:22 UTC, ashwindasr commented on art-bot.py
> +                'function': pr_info
Need to add example command to [show_help](https://github.com/openshift/art-bot/blob/0319f45138cf6efabc6a80c10a8aa80ecf1c133c/art-bot.py#L40) function as well.

2022-10-26 22:22 UTC, ashwindasr commented on artbotlib/pr_in_build.py
> +                self.so.say(f'PR {self.pr_url} has not been found in any `{self.version}` release')
Keeping the PR as a hyperlink `<{self.pr_ur}|PR>` could ensure more readability. Similarly we could also provide a link to the release and nightly as well, so that it would be easy for users to go to the release/nightly in question.

2022-10-27 10:32 UTC, locriandev commented on art-bot.py
> +                'function': pr_info
Fixed in https://github.com/openshift/art-bot/pull/35/commits/c6e14fbb36f9b0dbdb83084432fd6b9db9b3ea65

2022-10-27 10:51 UTC, locriandev commented on artbotlib/pr_in_build.py
> +                self.so.say(f'PR {self.pr_url} has not been found in any `{self.version}` release')
Done in https://github.com/openshift/art-bot/pull/35/commits/2697a3180102dd34c0b9493ca88b8adbd738cf9f

2022-10-27 11:10 UTC, locriandev commented
> We have the [github-distgit mapping code](https://github.com/openshift/art-bot/blob/0319f45138cf6efabc6a80c10a8aa80ecf1c133c/artbotlib/pipeline_image_util.py#L21) in the image-pipeline feature. I think we don't have more than 3 components building from the same repo, so we could check for all components and display if they are in releases or not. Even if we are getting the component name as input we'll have to check if the component actually exists before we proceed, so we can reuse the github-distgit mapping code.

The github-distgit is already being used [here](https://github.com/locriandev/art-bot/blob/ART-5067/artbotlib/pr_in_build.py#L44): right now, there's a check the fails if the repo is not mapped to any component. We can use that to check if a component exists too.

I don't like the idea of checking the PR for each component that maps to that repo: people are going to be asking about a specific component, the rest will just be noise. My plan is to enforce providing a component name where there is ambiguity.

2022-10-27 13:16 UTC, ashwindasr commented
> I don't like the idea of checking the PR for each component that maps to that repo: people are going to be asking about a specific component, the rest will just be noise. My plan is to enforce providing a component name where there is ambiguity.

That works. We can proceed like that.

2022-10-27 13:40 UTC, ashwindasr commented
> Is this needed for oc adm command?

I think the existing art-publish kubeconfig is too powerful and we don't need anything more than a read-only one, so Luke suggested that we update the scope. I'm a bit new to oc commands. So if it works for releases will it also work for nightlies? If its working, we can go ahead with the merge and update the scope later on.

2022-10-28 10:52 UTC, locriandev commented
> TODO before merging:
> 
> * Need to acquire read-only token for looking at nightlies and releases.

I don't think we need a cluster API token to get what we need about nightlies and releases:
```
oc image info $(oc adm release info registry.ci.openshift.org/ocp/release:4.12.0-0.nightly-2022-10-28-001703 --image-for vsphere-problem-detector) -o json
```
gives us what we need.

2022-11-02 19:37 UTC, ashwindasr requested changes

2022-11-02 20:04 UTC, locriandev commented on artbotlib/pr_in_build.py
> +                            f'please specify the one you\'re interested in and try again')
Yes, we should definitely improve our docs and provide extensive usage examples. Let's create a dedicated jira for that.

I'd rather redirect the user to a doc then provide an example query in the response

2022-11-03 10:27 UTC, locriandev commented on art-bot.py
> +                'regex': r'^pr info \s*(https://)*(github.com/)*(openshift/)*(?P<repo>[a-zA-Z0-9-]+)*(/pull/)*(?P<pr_id>\d+)(?: component (?P<component>[a-zA-Z0-9-]+))? in %(major_minor)s(?: for arch
Update regex in https://github.com/openshift/art-bot/pull/35/commits/be2428fd510ea4710a3f9c2d05a9b7a67f5651f8

2022-11-03 10:28 UTC, locriandev commented on artbotlib/pr_in_build.py
> +            so.say(f'`{self.arch}` is not a valid architecture: '
Fixed in https://github.com/openshift/art-bot/pull/35/commits/d8841542d2ba2336dce3ce606d2601f8fcc19ace

2022-11-03 18:01 UTC, locriandev commented on artbotlib/pr_in_build.py
> +            earliest_nightly, earliest_release = await asyncio.gather(*tasks, return_exceptions=True)
Turned out that this error is caused by GitHub API not returning 200 (it's probably something we wouldn't encounter in production, but you never know...); when this happens, `response.json()` raises an Exception that is returned as the async task result. [This has been fixed by](https://github.com/openshift/art-bot/pull/35/commits/a5cd308c544708d77abf00501f74b9743cba52e6):

1. checking the API request status code, and raising an exception if it is not 200
2. setting `return_exceptions=False` when gathering async tasks; this way, the exception is propagated and raised in the `run()` function, instead of being returned by the task
3. handling the exception and gracefully quitting; the user is warned with the error

2022-11-03 19:04 UTC, ashwindasr commented
/lgtm

2022-11-04 09:07 UTC, merged