Add pr in build feature
openshift/art-bot pull request #36
Opened 2022-11-04 17:37 UTC by ashwindasr

Feature to check if a PR has been included in a build ([ART-1877](https://issues.redhat.com/browse/ART-1877)).

Workflow:
- Find the commits including and after the merge commit.
- Check each commit from the oldest to newest if has an associated successful build in the database, and report the first successful build.
- If no successful builds, repeat the above steps, but instead look for a failed build, and report the first failed build.
- If no builds have been found, report back saying that a build hasn't started yet for the PR.

2022-11-10 08:31 UTC, locriandev requested changes

2022-11-10 08:31 UTC, locriandev commented on artbotlib/pr_in_build.py
> +
```suggestion
            return
        
        self.logger.info("No successful builds found given PR")
        failed_builds = self.build_from_commit("failure")
        if failed_builds:
            first_failure = failed_builds[0]
            self.logger.info(f"First failed build: {first_failure}")
            self.so.say(
                f"No successful build found. First failed build: <https://brewweb.engineering.redhat.com/brew/buildinfo?buildID={first_failure}|{first_failure}>")
            return
            
        self.logger.info(f"No builds have run yet.")
        self.so.say("No builds have started yet for the PR. Check again later.")

```

2022-11-10 08:31 UTC, locriandev commented on artbotlib/pr_in_build.py
> +
Suggesting this change to increase readability and keep indentantion level reasonable

2022-11-14 18:39 UTC, ashwindasr commented on artbotlib/pr_in_build.py
> +        successful_builds = self.build_from_commit("success")
Done! https://github.com/openshift/art-bot/pull/36/commits/cebf8969b7e558897d15ce0fc7cbf3a92e51a62b

2022-11-14 18:40 UTC, ashwindasr commented on artbotlib/pr_in_build.py
> +
Fixed https://github.com/openshift/art-bot/pull/36/commits/cebf8969b7e558897d15ce0fc7cbf3a92e51a62b

2022-11-15 07:40 UTC, locriandev commented
/lgtm

2022-11-15 18:27 UTC, merged