Add developer interface for art-bot
openshift/art-bot pull request #37
Opened 2022-11-04 18:39 UTC by ashwindasr

Preparing art-bot for migrating from classic slack app to the latest slack app. Currently slack is sending responses to both production and development environments as its using [RTM](https://api.slack.com/rtm). When we migrate to socket mode, slack will randomly send the responses to [any of the connections](https://api.slack.com/apis/connections/socket-implement#connections). Therefore developing using `@art-bot-dev` will no longer be possible.

It was proposed during team sync that an developer command line interface could remedy the situation, as we can test the regexes using that and in production, we'll connect to the actual slack object.

By setting a `RUN_ENV` variable in production, we can check to see if its a production, and if its not, we can just print out the responses.

Sample interface:
```
Welcome to the developer interface for Art-Bot.

Enter your command ('exit' to break): what's up
'what's up' did not match any regexes.

Enter your command ('exit' to break): hello
so.say:
---
Hi, @developer
---
Enter your command ('exit' to break): exit
Exiting...
```

2022-11-09 14:28 UTC, locriandev reviewed
I've tested a query like `what images build in 4.11`, the CLI crashed by `AttributeError`.

2022-11-09 14:30 UTC, locriandev commented
By wrapping the `command = input("Enter your command ('exit' to break): ")` with a `try/except` block we will let the user terminate the CLI by typing `CTRL^C`

2022-11-09 14:31 UTC, locriandev commented
I would rather not have to define and env var for production; maybe we can turn the logic around, by forcing the user to define `RUN_ENV=test` when needed?

2022-11-09 14:32 UTC, locriandev commented
I think it would be cleaner to have the CLI as a separate executable. We might move `regex_maps` outside the local scope (better if to a dedicated module) and create a `cli.py` that imports it

2022-11-09 17:41 UTC, ashwindasr commented
> I would rather not have to define and env var for production; maybe we can turn the logic around, by forcing the user to define `RUN_ENV=test` when needed?

Yes I first thought about that, but the issue is that if the developer forgets to add  `RUN_ENV=test` there will be two production instances. What about `RUN_ENV != production`, that should enforce the same constraint right?

2022-11-09 18:42 UTC, ashwindasr commented
> By wrapping the `command = input("Enter your command ('exit' to break): ")` with a `try/except` block we will let the user terminate the CLI by typing `CTRL^C`

I tried to do that, but it doesn't seem to be working, since we're waiting for an input `''` is going through.

2022-11-09 18:43 UTC, ashwindasr commented
> I've tested a query like `what images build in 4.11`, the CLI crashed by `AttributeError`.

It was because of the `SlackOutput` class. Instead of checking for production everytime, I created a new class which inherits from `SlackOutput` class and overrode the functions to just print.

2022-11-10 08:09 UTC, locriandev commented
> I tried to do that, but it doesn't seem to be working, since we're waiting for an input '' is going through.

CTRL^C works for me: https://github.com/ashwindasr/art-bot/compare/development-command-line-feature...locriandev:art-bot:development-command-line-feature

2022-11-10 08:11 UTC, locriandev commented
> > I would rather not have to define and env var for production; maybe we can turn the logic around, by forcing the user to define `RUN_ENV=test` when needed?
> 
> Yes I first thought about that, but the issue is that if the developer forgets to add `RUN_ENV=test` there will be two production instances and with the new slack bot, that can cause a lot of issues. We're actually doing this for art-dash to determine which env files to load.

I think this is another reason in favor of decoupling concerns. Our CLI applications does not need to know anything about Slack, it's just there to test out regex. Making it a separate executable would solve this issue

2022-11-10 14:22 UTC, ashwindasr commented
> CTRL^C works for me: [ashwindasr/art-bot@development-command-line-feature...locriandev:art-bot:development-command-line-feature](https://github.com/ashwindasr/art-bot/compare/development-command-line-feature...locriandev:art-bot:development-command-line-feature)

Ahh I see. I think its an issue with my setup. I was trying to remotely connect to the container using PyCharm for which Ctrl-C doesn't work, but when I run the script it seems to be working now. Will push the change thank you!

2022-11-10 14:22 UTC, ashwindasr commented
> > > I would rather not have to define and env var for production; maybe we can turn the logic around, by forcing the user to define `RUN_ENV=test` when needed?
> > 
> > 
> > Yes I first thought about that, but the issue is that if the developer forgets to add `RUN_ENV=test` there will be two production instances and with the new slack bot, that can cause a lot of issues. We're actually doing this for art-dash to determine which env files to load.
> 
> I think this is another reason in favor of decoupling concerns. Our CLI applications does not need to know anything about Slack, it's just there to test out regex. Making it a separate executable would solve this issue

Understood. Will create a new script.

2022-11-10 16:08 UTC, ashwindasr commented on art_bot_dev.py
> +art_bot = __import__("art-bot")
Since dashes are present in `art-bot.py`, we can't import functions from that file by saying `import art-bot`. We either have to rename the file to `art_bot.py` by replacing the dashes with underscores or use the `__import__` function, as used here. The renaming will result in a change at a lot of places including the deployment in production, but if that's the better way to go we can do that as well.

2022-11-10 17:14 UTC, ashwindasr commented
Need to set `NEEDS_KINIT` in production after merge.

2022-11-10 17:14 UTC, ashwindasr commented on art_bot_dev.py
> +art_bot = __import__("art-bot")
Decided to refactor after slack app migration.

2022-11-11 17:59 UTC, locriandev requested changes

2022-11-11 17:59 UTC, locriandev commented on artbotlib/slack_output.py
> +
Remove extra blank line (only one needed between class methods)

2022-11-11 17:59 UTC, locriandev commented on artbotlib/slack_output.py
> +
Remove extra blank line (only one needed between class methods)

2022-11-11 17:59 UTC, locriandev commented on artbotlib/slack_output.py
> +
Add another blank line (two needed between module-level functions)

2022-11-11 17:59 UTC, locriandev commented on artbotlib/slack_output.py
> +    def say(self, text, **msg_opts):
Add a blank line before method definition

2022-11-11 17:59 UTC, locriandev commented on artbotlib/slack_output.py
> +
Remove extra blank line (only one needed between class methods)

2022-11-11 17:59 UTC, locriandev commented on artbotlib/slack_output.py
> +        return "developer_channel"
Add a new line at the end of the file

2022-11-12 17:50 UTC, ashwindasr commented on artbotlib/slack_output.py
> +
Fixed in https://github.com/openshift/art-bot/pull/37/commits/843bc5d60bb27653934f62f5f2c40b89bb426753

2022-11-12 17:50 UTC, ashwindasr commented on artbotlib/slack_output.py
> +
Fixed in https://github.com/openshift/art-bot/pull/37/commits/843bc5d60bb27653934f62f5f2c40b89bb426753

2022-11-12 17:51 UTC, ashwindasr commented on artbotlib/slack_output.py
> +
Fixed in https://github.com/openshift/art-bot/pull/37/commits/843bc5d60bb27653934f62f5f2c40b89bb426753

2022-11-12 17:51 UTC, ashwindasr commented on artbotlib/slack_output.py
> +    def say(self, text, **msg_opts):
Fixed in https://github.com/openshift/art-bot/pull/37/commits/843bc5d60bb27653934f62f5f2c40b89bb426753

2022-11-12 17:51 UTC, ashwindasr commented on artbotlib/slack_output.py
> +
Fixed in https://github.com/openshift/art-bot/pull/37/commits/843bc5d60bb27653934f62f5f2c40b89bb426753

2022-11-12 17:51 UTC, ashwindasr commented on artbotlib/slack_output.py
> +        return "developer_channel"
Fixed in https://github.com/openshift/art-bot/pull/37/commits/843bc5d60bb27653934f62f5f2c40b89bb426753

2022-11-14 11:02 UTC, locriandev commented
/lgtm

2022-11-15 18:27 UTC, merged