[ART-1877] pr in build
openshift/art-bot pull request #41
Opened 2022-11-16 15:05 UTC by locriandev

Ref. https://issues.redhat.com/browse/ART-1877

2022-11-16 18:05 UTC, ashwindasr requested changes

2022-11-16 18:05 UTC, ashwindasr commented on art-bot.py
> +            },
This bit of code needs to be inside the `map_command_to_regex` function right? An issue during merge conflict?

2022-11-17 10:42 UTC, locriandev commented on art-bot.py
> +            },
Good catch, fixed in https://github.com/openshift/art-bot/pull/41/commits/ab662e1dc969f552152ce25b00d7e2525fae9981

2022-11-17 14:10 UTC, ashwindasr approved these changes
/lgtm

2022-11-17 14:17 UTC, merged